FROM node:22-slim

WORKDIR /app

RUN npm install -g pnpm@9.15.9

COPY . .

# Write a clean pnpm-workspace.yaml via Node to avoid shell quoting issues.
# The committed file uses Replit-specific pnpm settings that standard pnpm cannot parse.
RUN node -e "\
const fs = require('fs');\
fs.writeFileSync('pnpm-workspace.yaml',\
'packages:\n  - artifacts/api-server\n  - lib/api-zod\n  - lib/db\n');"

# Replace all catalog: references with explicit versions so no catalog feature is needed.
RUN sed -i 's|"drizzle-orm": "catalog:"|"drizzle-orm": "^0.45.2"|g' \
      artifacts/api-server/package.json lib/db/package.json && \
    sed -i 's|"@types/node": "catalog:"|"@types/node": "^22.0.0"|g' \
      artifacts/api-server/package.json lib/db/package.json && \
    sed -i 's|"zod": "catalog:"|"zod": "^3.25.76"|g' \
      lib/api-zod/package.json lib/db/package.json

# Delete the committed lockfile — it was generated by Replit's patched pnpm
# and is incompatible with standard pnpm
RUN rm -f pnpm-lock.yaml

RUN pnpm install --no-frozen-lockfile

RUN pnpm --filter @workspace/api-server run build

EXPOSE 5000

CMD ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]
