# syntax=docker/dockerfile:1
FROM node:22-slim

WORKDIR /app

RUN npm install -g pnpm@9.15.9

COPY . .

# Write a minimal Railway-compatible pnpm-workspace.yaml.
# The committed file contains Replit-specific settings (minimumReleaseAge)
# that standard pnpm cannot parse, breaking catalog resolution entirely.
# Overwriting it here guarantees the correct file is used regardless of cache.
RUN cat > pnpm-workspace.yaml <<'WSEOF'
packages:
  - artifacts/api-server
  - lib/api-zod
  - lib/db

catalog:
  '@types/node': ^22.0.0
  drizzle-orm: ^0.45.2
  zod: ^3.25.76

autoInstallPeers: false
WSEOF

# Delete the old lockfile — it was generated by a Replit-patched pnpm
# and is incompatible with standard pnpm
RUN rm -f pnpm-lock.yaml

RUN pnpm install --no-frozen-lockfile

RUN pnpm --filter @workspace/api-server run build

EXPOSE 5000

CMD ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]
